server:
  port: 8081

spring:
  application:
    name: map-outage-scheduler

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

# --- Your knobs ---
scheduler:
  interval: 20m           # send cadence
  duration: 2h            # total test window
  maxOutagesTotal: 20
  maxReachPctByMaxHour: 0.6
  avgNodesPerFile: 20
  ramp:
    shape: sigmoid        # linear|exp|sigmoid
    a: 10
    k: 2.5

# Sample file on the same server (relative or absolute path)
sample:
  path: /Users/Agopalakrishnan/Downloads/schedulePerf-war-ec2-pregen-java11/src/main/resources/sample/sample.json

# Folder to PRE-GENERATE all payload files, and from which sender will pick
output:
  dir: /Users/Agopalakrishnan/Downloads/PerfTest/Samples

target:
  endpoint: https://YOUR_DATAFEED_URL
  auth:
    type: bearer          # bearer|header|none
    token: YOUR_TOKEN

retry:
  maxAttempts: 5
  backoffSeconds: 1
send:
  enabled: false